2019-August-02 - dev-meeting
============================

### accessing google spreadsheets

- python3 style: [file_link](https://github.com/birkin/book_locator_project/blob/2593df456f498ae8eda65e3d5587f7055ec9049e/book_locator_app/lib/index.py)

- A main difference...

        # credentials = SignedJwtAssertionCredentials(json_key['client_email'], json_key['private_key'].encode(), scope)  # py2
        credentials = ServiceAccountCredentials.from_json_keyfile_name( settings_app.GSHEET_KEY_PATH, scope )  # py3

    I did try the email/private-key/scope params, and the docs indicated it should have worked, but it didn't -- and tutorials pointed to loading the whole json-key file.

- Issue...

    I was able to access the doc, see title and other info about the multile worksheets in the doc -- but could _not_ actually load and read data from an individual worksheet.

    Tried a few things from googling, and ended up reverting to an older version of [gspread](https://gspread.readthedocs.io/en/latest/), a python library for doing this sort of thing.

    Apparently, the newer versions of gspread use, behind-the-scenes, version 4 of google doc/sheet APIs (which are supposed to be faster). The older version of gspread uses version 3 of those APIs, and is deprecated. So... invitation for folk to gather in the future to try to get the newer version of gspread working!

---


### when sort() doesn't

- python2

        >>> lst = [ 1, 'a', 2 ]
        >>>
        >>> lst.sort()
        >>>
        >>> lst
        [1, 2, 'a']
        >>>
        >>> lst = [ 1, None, 2 ]
        >>>
        >>> lst.sort()
        >>>
        >>> lst
        [None, 1, 2]


- python3

        >>> lst = [ 1, 'a', 2 ]
        >>>
        >>> lst.sort()
        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
        TypeError: '<' not supported between instances of 'str' and 'int'
        >>>
        >>> lst = [ 1, None, 2 ]
        >>>
        >>> lst.sort()
        Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
        TypeError: '<' not supported between instances of 'NoneType' and 'int'

    The `None` scenario was the one I came across. My SO-inspired solution, a list-comprehension: [code-link](https://github.com/birkin/book_locator_project/blob/2593df456f498ae8eda65e3d5587f7055ec9049e/book_locator_app/lib/index.py#L260-L262)

        >>> cleaned_lst = [ x for x in lst if x ]
        >>> cleaned_lst.sort()

    - Ok, this is cool... at the last minute I figured I'd add a link to info on python [list-comprehensions](https://python-3-patterns-idioms-test.readthedocs.io/en/latest/Comprehensions.html), for the myriad readers of these dev-notes. The link above has this...

        _"Comprehensions are constructs that allow sequences to be built from other sequences."_

        Ok, fine, nice and concise. But __then__...

        _"Python 2.0 introduced list comprehensions and Python 3.0 comes with dictionary and set comprehensions."_

        What‽

        I don't work with set's much, but _dictionary-comprehensions_ ‽‽‽

        B.C. -- how about a report on those next week!


---

---
